### ISSUE TITLE
Disembowel Timer Issue

### ISSUE THREAD

**Issue by seelroy** [Zeffuro/Zeffuro-s-Trigger-Repository#1]
The timer for the Dragoon ability Disembowel does not work. I believe it may be an issue with the regex as I could not get the regex to match the logs whatsoever in regex101, though this could be due to my ignorance with regex.

**Comment by Zeffuro** [comment]
I forgot to set the trigger to FFXIV Network Events (I'll be changing the regex back to normal log lines later), for now it should be working again. Please try it out and let me know.

**Comment by seelroy** [comment]
Works perfectly now! Thank you for the speedy fix! :)
